name = "shard_categorytheory"
defaultTargets = ["ShardImports"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_lib]]
name = "ShardImports"
