# neon/build_seed_sql.py
# Regenerates neon/seed.sql from shards.json + scripts/mathlib_files.txt -
# the same real module list generate_shards.py uses, so the DB mapping and
# the actual Docker images never drift apart. Re-run after editing
# shards.json, RENDER_SERVICE_NAMES below, or refreshing mathlib_files.txt.
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Must match the `name:` fields in render.yaml - Render URLs default to
# https://<service-name>.onrender.com. Verify after first deploy; if Render
# appended a suffix due to a name collision, patch the `shards` table's
# render_url column with the real URL instead of re-seeding.
RENDER_SERVICE_NAMES = {
    "algebra": "lean-shard-algebra",
    "analysis": "lean-shard-analysis",
    "numbertheory": "lean-shard-numbertheory",
    "topology": "lean-shard-topology",
    "categorytheory": "lean-shard-categorytheory",
}


def module_name(path: str) -> str:
    return path[: -len(".lean")].replace("/", ".")


def matches(mod: str, namespaces: list[str]) -> bool:
    return any(mod == ns or mod.startswith(ns + ".") for ns in namespaces)


def main():
    cfg = json.loads((ROOT / "shards.json").read_text(encoding="utf-8"))
    all_mods = [
        module_name(l.strip())
        for l in (ROOT / "scripts" / "mathlib_files.txt").read_text(encoding="utf-8").splitlines()
        if l.strip()
    ]
    common_ns = cfg["common_namespaces"]

    lines = ["-- generated by neon/build_seed_sql.py - do not hand-edit", ""]

    lines.append("INSERT INTO shards (id, render_url, namespaces) VALUES")
    shard_rows = []
    for shard in cfg["shards"]:
        sid = shard["id"]
        url = f"https://{RENDER_SERVICE_NAMES[sid]}.onrender.com"
        ns_array = "ARRAY[" + ",".join(f"'{n}'" for n in common_ns + shard["namespaces"]) + "]"
        shard_rows.append(f"  ('{sid}', '{url}', {ns_array})")
    lines.append(",\n".join(shard_rows))
    lines.append("ON CONFLICT (id) DO UPDATE SET render_url = EXCLUDED.render_url, namespaces = EXCLUDED.namespaces;")
    lines.append("")

    # Only seed modules that live in a shard's OWN namespaces here. A module
    # covered only by common_ns (e.g. Mathlib.Data.Nat.Prime.Basic) is valid
    # in every shard - if it were included per-shard using common_ns + own
    # namespaces, the last shard processed would silently win for every
    # common module (confirmed bug: routed a pure Mathlib.Data.* file to
    # categorytheory - one of the slower shards - instead of treating it as
    # shard-agnostic). Leaving common-only modules OUT of this table makes
    # router/server.py's fallback_shard() correctly resolve them to
    # "__common_only__" instead.
    assigned = {}
    for shard in cfg["shards"]:
        for m in all_mods:
            if matches(m, shard["namespaces"]):
                assigned[m] = shard["id"]

    lines.append("INSERT INTO modules (name, shard_id) VALUES")
    mod_rows = [f"  ('{name}', '{sid}')" for name, sid in sorted(assigned.items())]
    lines.append(",\n".join(mod_rows))
    lines.append("ON CONFLICT (name) DO UPDATE SET shard_id = EXCLUDED.shard_id;")
    lines.append("")

    out = ROOT / "neon" / "seed.sql"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out} - {len(shard_rows)} shards, {len(mod_rows)} modules")


if __name__ == "__main__":
    main()
